server:
  port: 8090
spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true

logging:
  file: /var/log/moglix/integration-consumer/app.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.batch: INFO
    com.moglix: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO


#MySQL config NOT BEING USED CURRENTLY
#spring.datasource.url=jdbc:mysql://localhost:3306/integrator
#spring.datasource.username=root
#spring.datasource.password=6979
#spring.jpa.show-sql=true
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext